# System utilities
SYSTEM_UTILS=(
  base
  base-devel
  bash-completion
  ly
  btop
  neofetch
  zip
  unzip
  wget
  curl
  brightnessctl
  thunar
  slurp
  scrcpy
  plymouth
  python-i3ipc
  fuse2
  engrampa
)

# Development tools
DEV_TOOLS=(
  bat
  neovim
  foot
  git
)

# System maintenance
MAINTENANCE=(
  gnome-disk-utility
)

# Desktop environment
DESKTOP=(
sway
swayidle
swaybg
swaylock
)

# Media packages
MEDIA=(
  mpv
  xfce4-screenshooter
  gvfs-mtp
  pavucontrol
  pipewire-pulse
)

# Fonts

# Services to enable
SERVICES=(
  ly.service
  NetworkManager.service
)

YAY=(
wlogout
